CREATE TABLE "Regiao" (
    codigo INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    nome VARCHAR(31) NOT NULL
);

CREATE TABLE "Estado" (
    codigo INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    nome VARCHAR(63) NOT NULL,
    uf CHAR(2) NOT NULL,
    codigoRegiao INT NOT NULL
);

CREATE TABLE "Municipio" (
    codigo INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    uf CHAR(2) NOT NULL
);
